### ISSUE TITLE
При выборе типа легенды "без легенды" заполнение полей не меняется

### ISSUE THREAD

**Issue by urticaolga** [skypro-fastdev/skypro-resume-builder#10]
Шаги:
1.Зайти в генератор резюме https://skypro-resume-builder-dev.onrender.com/
2.Перевести переключатель "добавить легенду" в активное положение
3.В появившемся выпадающем списке выбрать тип легенды
Ожидаемый результат: происходит автоматическое заполнение пользовательских полей соответственно типу легенды
Фактический результат: при выборе типа легенды "без легенды"  автоматическое заполнение полей остается как при предыдущем типе легенды и отображается в готовом резюме после генерации
Среда: Chromium версия 131.0.6778.8

![Снимок экрана от 2024-12-05 14-35-20](https://github.com/user-attachments/assets/4a7aa88e-52f3-4086-8227-99602931384b)

**Comment by kushedow** [comment]
Убрать тип легенды "Без легенды"

**Comment by urticaolga** [comment]
Посмотрела, типа легенды "без легенды" нет, соответственно бага нет
