### ISSUE TITLE
Отсутствует предупреждение о неправильном типе файла при загрузке фото

### ISSUE THREAD

**Issue by urticaolga** [skypro-fastdev/skypro-resume-builder#4]
Шаги:
1. Зайти в генератор резюме https://skypro-resume-builder.onrender.com/?code=GHJ3QSI2GORQUFFJS7AU6450993G6RTFEG7OINV8KESTKG5EB2ICUBF66T6OSGCM
2. Заполнить резюме валидными данными 
3. Авторизоваться на HH
4. Загрузить файл с неправильным форматом

Ожидаемый результат: появляется предупреждение о неверном типе файла для загрузки
Фактический результат: предупреждения нет, ошибка в консоли 400
Среда: Chromium версия 131.0.6778.8

![Снимок экрана от 2024-12-03 14-54-38](https://github.com/user-attachments/assets/fae6afb7-88d9-4764-b386-975cc4f7cb86)

**Comment by kushedow** [comment]
Небольшое замечание: 

В шагах воспроизведения бага пропущен шаг подтверждения аккаунта на HH – без него поле загрузки не активируется.

**Comment by kushedow** [comment]
Добавлена проверка на расширение загружаемого фото.

![image](https://github.com/user-attachments/assets/0425cfc4-5313-4aef-9dca-c87dddea7118)
