### ISSUE TITLE
Появляется сообщение об ошибке при активации легенды 

### ISSUE THREAD

**Issue by urticaolga** [skypro-fastdev/skypro-resume-builder#6]
Шаги:
1. Зайти в генератор резюме https://skypro-resume-builder-dev.onrender.com/
2. Перевести переключатель "добавить легенду" в активное положение
Ожидаемый результат: переключатель переведен в активное положение открылся блок для создания легенды
Фактический результат: переключатель не переведен в активное положение, появилась ошибка даты, переключатель срабатывает, если нажать ok в сообщении об ошибке
Среда: Chromium версия 131.0.6778.8

![Снимок экрана от 2024-12-04 23-21-53](https://github.com/user-attachments/assets/65ca493b-8c1a-437d-9876-3caeec7be594)

**Comment by kushedow** [comment]
Исправлено

![Image](https://github.com/user-attachments/assets/a8fcb877-9adc-49b6-8904-34b242467c8c)

**Comment by urticaolga** [comment]
Посмотрела, сообщения об ошибке при активации легенды нет
